In [1]:
import pandas as pd
df = pd.read_csv('swiggy.csv', on_bad_lines='skip')
df = df.drop(columns=['link'])
df.head()

,id,name,city,rating,rating_count,cost,cuisine,lic_no,address,menu
0,567335,AB FOODS POINT,Abohar,--,Too Few Ratings,₹ 200,"Beverages,Pizzas",22122652000138,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50+ ratings,₹ 200,"Sweets,Bakery",12117201000112,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100+ ratings,₹ 100,Beverages,22121652000190,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20+ ratings,₹ 250,"Fast Food,Indian",22119652000167,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,--,Too Few Ratings,₹ 250,"Italian-American,Fast Food",12122201000053,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [2]:
df.describe()

                  id
count  148541.000000
mean   363466.378912
std    167890.977174
min       211.000000
25%    233320.000000
50%    412628.000000
75%    502223.000000
max    581031.000000

In [3]:
original_rows_before_duplicates = df.shape[0]
df.drop_duplicates(inplace=True)
rows_removed_duplicates = original_rows_before_duplicates - df.shape[0]

print(f"Number of rows removed due to duplicates: {rows_removed_duplicates}")
print(f"DataFrame shape after dropping duplicates: {df.shape}")

Number of rows removed due to duplicates: 0
DataFrame shape after dropping duplicates: (148541, 10)

In [4]:
print("Missing values per column before dropping:")
print(df.isnull().sum())

original_rows_before_na = df.shape[0]
df.dropna(inplace=True)
rows_removed_due_to_na = original_rows_before_na - df.shape[0]

print(f"\nNumber of rows removed due to missing values: {rows_removed_due_to_na}")
print(f"DataFrame shape after dropping missing values: {df.shape}")

Missing values per column before dropping:
id                0
name             86
city              0
rating           86
rating_count     86
cost            131
cuisine          99
lic_no          229
address          86
menu              0
dtype: int64

Number of rows removed due to missing values: 286
DataFrame shape after dropping missing values: (148255, 10)

In [5]:
df.to_csv('cleaned_data.csv', index=False)
print("Cleaned data saved to 'cleaned_data.csv'")

Cleaned data saved to 'cleaned_data.csv'

In [6]:
df=pd.read_csv('cleaned_data.csv')
df.head()

print("\n--- Verifying Cleaned Data ---")
num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")
missing_values_count = df.isnull().sum().sum()
print(f"Number of missing values: {missing_values_count}")

if num_duplicates == 0 and missing_values_count == 0:
    print("The data appears to be clean (no duplicates or missing values).")
else:
    print("Warning: Duplicates or missing values found, review cleaning steps.")

print(f"Current DataFrame shape: {df.shape}")

--- Verifying Cleaned Data ---
Number of duplicate rows: 0
Number of missing values: 0
The data appears to be clean (no duplicates or missing values).
Current DataFrame shape: (148255, 10)

In [7]:
df = pd.read_csv('cleaned_data.csv')
df.head()

,id,name,city,rating,rating_count,cost,cuisine,lic_no,address,menu
0,567335,AB FOODS POINT,Abohar,--,Too Few Ratings,₹ 200,"Beverages,Pizzas",22122652000138,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50+ ratings,₹ 200,"Sweets,Bakery",12117201000112,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100+ ratings,₹ 100,Beverages,22121652000190,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20+ ratings,₹ 250,"Fast Food,Indian",22119652000167,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,--,Too Few Ratings,₹ 250,"Italian-American,Fast Food",12122201000053,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [8]:
print("Unique values in 'city':", df['city'].nunique())
print("Unique values in 'rating':", df['rating'].nunique())
print("Unique values in 'rating_count':", df['rating_count'].nunique())
print("Unique values in 'cost':", df['cost'].nunique())
print("Unique values in 'cuisine':", df['cuisine'].nunique())

print("\nValue counts for 'rating':")
print(df['rating'].value_counts())

print("\nValue counts for 'rating_count':")
print(df['rating_count'].value_counts().head(10))

print("\nValue counts for 'cost':")
print(df['cost'].value_counts().head(10))

Unique values in 'city': 821
Unique values in 'rating': 42
Unique values in 'rating_count': 8
Unique values in 'cost': 363
Unique values in 'cuisine': 2131

Value counts for 'rating':
rating
--     86912
4.0     6524
4.1     6288
4.2     5811
3.8     5728
3.9     5428
4.3     5005
3.7     4239
4.4     3145
3.5     2958
3.6     2918
3.4     1878
3.3     1796
4.5     1775
4.6     1332
3.2     1199
3.0      858
3.1      790
4.7      648
2.8      473
2.9      471
4.8      338
2.7      325
2.5      220
5.0      209
2.6      207
4.9      172
2.3      128
2.4      118
2.2       89
2.0       72
2.1       61
1.9       46
1.8       27
1.5       18
1.6       17
1.7       13
1.4       10
1.2        4
1.3        3
1.1        1
1.0        1
Name: count, dtype: int64

Value counts for 'rating_count':
rating_count
Too Few Ratings    86912
20+ ratings        21604
100+ ratings       20514
50+ ratings        11985
500+ ratings        4390
1K+ ratings         2737
5K+ ratings           98
10K+ ratings          15
Name: count, dtype: int64

Value counts for 'cost':
cost
₹ 200    38590
₹ 300    29684
₹ 250    19725
₹ 150    12076
₹ 400    11698
₹ 500     6375
₹ 350     6288
₹ 100     6178
₹ 600     2555
₹ 450     1455
Name: count, dtype: int64

In [9]:
df['rating'] = df['rating'].replace('--', None)
df['rating'] = pd.to_numeric(df['rating'])

print("Data type of 'rating' after conversion:", df['rating'].dtype)
print("Value counts for 'rating' after conversion (top 10):\n", df['rating'].value_counts(dropna=False).head(10))

Data type of 'rating' after conversion: float64
Value counts for 'rating' after conversion (top 10):
 rating
NaN    86912
4.0     6524
4.1     6288
4.2     5811
3.8     5728
3.9     5428
4.3     5005
3.7     4239
4.4     3145
3.5     2958
Name: count, dtype: int64

In [10]:
def parse_rating_count(count_str):
    if isinstance(count_str, (int, float)):
        return float(count_str)
    
    if count_str == 'Too Few Ratings':
        return 0
    elif isinstance(count_str, str) and '+' in count_str:
        count_str = count_str.replace(' ratings', '').replace('+', '')
        if 'K' in count_str:
            return float(count_str.replace('K', '')) * 1000
        else:
            return float(count_str)
    
    try:
        return float(count_str)
    except (ValueError, TypeError):
        return 0  

df['rating_count'] = df['rating_count'].apply(parse_rating_count)

print("Data type of 'rating_count' after conversion:", df['rating_count'].dtype)
print("Value counts for 'rating_count' after conversion (top 10):\n", df['rating_count'].value_counts().head(10))

Data type of 'rating_count' after conversion: float64
Value counts for 'rating_count' after conversion (top 10):
 rating_count
0.0        86912
20.0       21604
100.0      20514
50.0       11985
500.0       4390
1000.0      2737
5000.0        98
10000.0       15
Name: count, dtype: int64

In [11]:
df['cost'] = df['cost'].str.replace('₹ ', '').astype(float)

print("Data type of 'cost' after conversion:", df['cost'].dtype)
print("Value counts for 'cost' after conversion (top 10):\n", df['cost'].value_counts().head(10))

Data type of 'cost' after conversion: float64
Value counts for 'cost' after conversion (top 10):
 cost
200.0    38590
300.0    29684
250.0    19725
150.0    12076
400.0    11698
500.0     6375
350.0     6288
100.0     6178
600.0     2555
450.0     1455
Name: count, dtype: int64

In [12]:
print("DataFrame Info after type conversions:")
df.info()

DataFrame Info after type conversions:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148255 entries, 0 to 148254
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            148255 non-null  int64
 1   name          148255 non-null  object
 2   city          148255 non-null  object
 3   rating        61343 non-null   float64
 4   rating_count  148255 non-null  float64
 5   cost          148255 non-null  float64
 6   cuisine       148255 non-null  object
 7   lic_no        148255 non-null  object
 8   address       148255 non-null  object
 9   menu          148255 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 11.3+ MB

In [13]:
if 'cuisine' in df.columns:
    unique_cuisines = df['cuisine'].str.split(',').explode().str.strip().unique()
    print(f"Number of unique cuisines: {len(unique_cuisines)}")
    print(f"First 10 unique cuisines: {unique_cuisines[:10]}")
else:
    print("Error: The 'cuisine' column is not found in the DataFrame. It might have been removed during preprocessing.")
    # If the `unique_cuisines` variable from a previous successful run is available, display it.
    if 'unique_cuisines' in globals():
        print(f"Previously extracted unique cuisines (count: {len(unique_cuisines)}):")
        print(f"First 10: {unique_cuisines[:10]}")
    else:
        print("No previously extracted unique cuisines data is available.")

Number of unique cuisines: 126
First 10 unique cuisines: ['Beverages' 'Pizzas' 'Sweets' 'Bakery' 'Fast Food' 'Indian'
 'Italian-American' 'Continental' 'North Indian' 'Snacks']

In [14]:
from sklearn.preprocessing import MultiLabelBinarizer
import pandas as pd
from typing import List

def encode_cuisine_column(df: pd.DataFrame, cuisine_col: str = 'cuisine') -> pd.DataFrame:
    """
    One-hot encodes the cuisine column which contains comma-separated values.
    
    Args:
        df (pd.DataFrame): Input DataFrame containing the cuisine column
        cuisine_col (str, optional): Name of the column containing cuisine data. Defaults to 'cuisine'.
    
    Returns:
        pd.DataFrame: Original DataFrame with added one-hot encoded cuisine columns
    """
    # Clean and split the cuisine strings
    cuisine_lists = df[cuisine_col].str.split(',').apply(lambda x: [item.strip() for item in x])
    
    # Initialize and fit the MultiLabelBinarizer
    mlb = MultiLabelBinarizer()
    cuisine_encoded = pd.DataFrame(
        mlb.fit_transform(cuisine_lists),
        columns=[f"cuisine_{cls}" for cls in mlb.classes_],  # Add 'cuisine_' prefix to avoid column name conflicts
        index=df.index
    )
    
    # Join the encoded columns to the original DataFrame
    result_df = pd.concat([df, cuisine_encoded], axis=1)  # Using concat instead of join for more control
    
    # Display information about the transformation
    print(f"Shape of DataFrame after cuisine encoding: {result_df.shape}")
    print("First 5 rows of encoded cuisines:")
    print(cuisine_encoded.head())  # Show only the encoded part
    
    return result_df

# Apply the function to encode the cuisine column
df = encode_cuisine_column(df)

Shape of DataFrame after cuisine encoding: (148255, 136)
First 5 rows of encoded cuisines:
   cuisine_8:15 To 11:30 Pm  cuisine_Afghani  cuisine_African  \
0                         0                0                0
1                         0                0                0
2                         0                0                0
3                         0                0                0
4                         0                0                0

   cuisine_American  cuisine_Andhra  cuisine_Arabian  cuisine_Asian  \
0                 0               0                0              0
1                 0               0                0              0
2                 0               0                0              0
3                 0               0                0              0
4                 0               0                0              0

   cuisine_Assamese  cuisine_Attractive Combos Available  cuisine_Australian  \
0                 0                                    0                   0
1                 0                                    0                   0
2                 0                                    0                   0
3                 0                                    0                   0
4                 0                                    0                   0

   ...  cuisine_Thai  cuisine_Thalis  cuisine_Tibetan  cuisine_Tribal  \
0  ...             0               0                0               0
1  ...             0               0                0               0
2  ...             0               0                0               0
3  ...             0               0                0               0
4  ...             0               0                0               0

   cuisine_Turkish  cuisine_Use Code JUMBO30 to avail  \
0                0                                  0
1                0                                  0
2                0                                  0
3                0                                  0
4                0                                  0

   cuisine_Use code XPRESS121 to avail.  cuisine_Vietnamese  cuisine_Waffle  \
0                                     0                   0               0
1                                     0                   0               0
2                                     0                   0               0
3                                     0                   0               0
4                                     0                   0               0

   cuisine_indian
0               0
1               0
2               0
3               0
4               0

[5 rows x 126 columns]

In [15]:
df = pd.get_dummies(df, columns=['city'], prefix='city')

print("Shape of DataFrame after city encoding:", df.shape)
print("First 5 rows of city encoded columns:")
print(df.filter(like='city_').head())

Shape of DataFrame after city encoding: (148255, 956)
First 5 rows of city encoded columns:
   city_Abids & Koti,Hyderabad  city_Abohar  city_Adajan,Surat  city_Adilabad  \
0                        False         True              False          False
1                        False         True              False          False
2                        False         True              False          False
3                        False         True              False          False
4                        False         True              False          False

   city_Adityapur  city_Adoni  city_Adyar,Chennai  city_Agartala  city_Agra  \
0           False       False               False          False      False
1           False       False               False          False      False
2           False       False               False          False      False
3           False       False               False          False      False
4           False       False               False          False      False

   city_Ahmednagar  ...  city_Washim  city_West Chd,Chandigarh  \
0            False  ...        False                     False
1            False  ...        False                     False
2            False  ...        False                     False
3            False  ...        False                     False
4            False  ...        False                     False

   city_West Marredpally,Hyderabad  city_Whitefield,Bangalore  \
0                            False                      False
1                            False                      False
2                            False                      False
3                            False                      False
4                            False                      False

   city_Yamuna-nagar  city_Yavatmal  city_Yelahanka,Bangalore  \
0              False          False                     False
1              False          False                     False
2              False          False                     False
3              False          False                     False
4              False          False                     False

   city_Yeshwanthpur,Bangalore  city_Zirakpur,Chandigarh  \
0                        False                     False
1                        False                     False
2                        False                     False
3                        False                     False
4                        False                     False

   city_sohna road,Gurgaon
0                    False
1                    False
2                    False
3                    False
4                    False

[5 rows x 821 columns]

In [16]:
import pickle
from typing import Any
import os
from sklearn.preprocessing import MultiLabelBinarizer  # Import the MultiLabelBinarizer class

def save_pickle_object(obj: Any, filepath: str) -> None:
    """
    Save an object to a pickle file.
    
    Args:
        obj (Any): The object to save.
        filepath (str): Path where the pickle file will be saved.
        
    Raises:
        IOError: If there's an issue writing to the file.
    """
    try:
        # Create directory if it doesn't exist
        directory = os.path.dirname(filepath)
        if directory and not os.path.exists(directory):
            os.makedirs(directory)
            
        # Save the object
        with open(filepath, 'wb') as file:
            pickle.dump(obj, file)
        print(f"Object successfully saved to '{filepath}'")
    except Exception as e:
        print(f"Error saving object to '{filepath}': {str(e)}")
        raise

# Create and fit a MultiLabelBinarizer instance before saving it
mlb = MultiLabelBinarizer()  # Define the mlb variable
# Typically you would fit the binarizer with some data here
# mlb.fit(your_data)

# Save the MultiLabelBinarizer
save_pickle_object(mlb, 'encoder.pkl')

Object successfully saved to 'encoder.pkl'

In [17]:
print("DataFrame Info after all encoding steps:")
df.info()

DataFrame Info after all encoding steps:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148255 entries, 0 to 148254
Columns: 956 entries, id to city_sohna road,Gurgaon
dtypes: bool(821), float64(3), int64(127), object(5)
memory usage: 268.8+ MB

In [18]:
object_columns = df.select_dtypes(include='object').columns
print(f"Non-numerical columns identified: {list(object_columns)}")

df = df.drop(columns=object_columns)

print("DataFrame Info after dropping non-numerical columns:")
df.info()

Non-numerical columns identified: ['name', 'cuisine', 'lic_no', 'address', 'menu']
DataFrame Info after dropping non-numerical columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148255 entries, 0 to 148254
Columns: 951 entries, id to city_sohna road,Gurgaon
dtypes: bool(821), float64(3), int64(127)
memory usage: 263.1 MB

In [19]:
df.to_csv('encoded_data.csv', index=False)
print("Preprocessed data saved to 'encoded_data.csv'")

Preprocessed data saved to 'encoded_data.csv'

In [20]:
import pickle
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# Example cuisine data
example_cuisine_data = [
    ['North Indian', 'Fast Food'],
    ['Italian', 'Pizzas', 'Beverages'],
    ['South Indian'],
    ['Fast Food', 'Snacks', 'Chinese']
]

# Create and fit the encoder
mlb = MultiLabelBinarizer()
mlb.fit(example_cuisine_data)

# Save the encoder (optional)
with open('encoder.pkl', 'wb') as file:
    pickle.dump(mlb, file)

# Now use the encoder
encoded_data = mlb.transform(example_cuisine_data)
encoded_df = pd.DataFrame(encoded_data, columns=mlb.classes_)

print("Encoded cuisine data (first 5 rows if more exist):")
print(encoded_df.head())

Encoded cuisine data (first 5 rows if more exist):
   Beverages  Chinese  Fast Food  Italian  North Indian  Pizzas  Snacks  \
0          0        0          1        0             1       0       0
1          1        0          0        1             0       1       0
2          0        0          0        0             0       0       0
3          0        1          1        0             0       0       1

   South Indian
0             0
1             0
2             1
3             0

In [21]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import NearestNeighbors

# 1. Load Data
df = pd.read_csv('cleaned_data.csv', on_bad_lines='skip')

# 2. Preprocessing & Encoding
# Clean 'cost': Remove '₹' and whitespace, convert to numeric
df['cost_clean'] = df['cost'].astype(str).str.replace('₹', '').str.strip()
df['cost_clean'] = pd.to_numeric(df['cost_clean'], errors='coerce').fillna(0)

# Clean 'rating': Convert to numeric, handle '--' or errors
df['rating_clean'] = pd.to_numeric(df['rating'], errors='coerce').fillna(0)

# Encode 'cuisine': One-Hot Encoding (handling comma-separated values)
cuisine_dummies = df['cuisine'].str.get_dummies(sep=',')

# Normalize numerical features
scaler = MinMaxScaler()
numerical_features = scaler.fit_transform(df[['cost_clean', 'rating_clean']])
numerical_df = pd.DataFrame(numerical_features, columns=['cost_norm', 'rating_norm'], index=df.index)

# Combine all features into the final encoded dataframe
df_encoded = pd.concat([numerical_df, cuisine_dummies], axis=1)

print(f"Data Processed. Features shape: {df_encoded.shape}")

# 3. Use NearestNeighbors instead of computing the full similarity matrix
# This is much more memory efficient for large datasets
model = NearestNeighbors(n_neighbors=6, algorithm='brute', metric='cosine')  # 6 because we include the restaurant itself
model.fit(df_encoded)

# 4. Define Recommendation Function
def get_recommendations(restaurant_name, df, model, top_n=5):
    """
    Finds similar restaurants using NearestNeighbors model
    """
    # Check if restaurant exists
    if restaurant_name not in df['name'].values:
        return f"Restaurant '{restaurant_name}' not found."

    # Get the index of the restaurant
    idx = df[df['name'] == restaurant_name].index[0]
    
    # Get the features for this restaurant
    restaurant_features = df_encoded.iloc[idx].values.reshape(1, -1)
    
    # Find nearest neighbors
    distances, indices = model.kneighbors(restaurant_features)
    
    # Convert distances to similarity scores (1 - distance)
    similarity_scores = 1 - distances.flatten()
    
    # Skip the first result (the restaurant itself)
    top_indices = indices.flatten()[1:top_n+1]
    top_scores = similarity_scores[1:top_n+1]

    # Map back to original data
    result = df.iloc[top_indices][['name', 'city', 'cuisine', 'cost', 'rating']].copy()
    result['similarity_score'] = top_scores  # Add score for reference

    return result

# 5. Usage Example
sample_restaurant = df['name'].iloc[0]
print(f"\n--- Recommendations for: {sample_restaurant} ---")

recommendations = get_recommendations(sample_restaurant, df, model)
print(recommendations)

Data Processed. Features shape: (148255, 129)

--- Recommendations for: AB FOODS POINT ---

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

                              name                     city           cuisine  \
32428                 Domnik Pizza  North Mohali,Chandigarh  Pizzas,Beverages
55307                 Tahalka Cafe             Rohini,Delhi  Beverages,Pizzas
6872                     Pizza Pie                 Amritsar  Pizzas,Beverages
32522               DOMINICS PIZZA  North Mohali,Chandigarh  Pizzas,Beverages
6929   Kruncheez Cafe & Patisserie                    Anand  Beverages,Pizzas

        cost rating  similarity_score
32428  ₹ 200     --               1.0
55307  ₹ 200     --               1.0
6872   ₹ 200     --               1.0
32522  ₹ 200     --               1.0
6929   ₹ 200     --               1.0

In [22]:
%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Page Configuration ---
st.set_page_config(page_title="Restaurant Recommender", layout="wide", page_icon="🍴")

# --- 2. Data Loading & Cleaning ---
@st.cache_data
def load_data():
    try:
        # Load data
        df = pd.read_csv('cleaned_data.csv')
        
        # Standardize column names (lowercase and no spaces)
        df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]

        # Clean 'cost' column: Remove '₹' and commas, convert to numeric
        if 'cost' in df.columns:
            df['price'] = df['cost'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
            df['price'] = pd.to_numeric(df['price'], errors='coerce')
        
        # Clean 'rating' column: Convert '--' or 'Too Few Ratings' to NaN, then numeric
        if 'rating' in df.columns:
            df['rating_numeric'] = pd.to_numeric(df['rating'], errors='coerce').fillna(0.0)
        
        # Clean 'cuisine' column
        df['cuisine'] = df['cuisine'].fillna('Not Specified')
        
        return df
    except Exception as e:
        st.error(f"Error loading CSV: {e}")
        return pd.DataFrame()

# Initialize Data
df = load_data()

if df.empty:
    st.error("Could not load 'cleaned_data.csv'. Please ensure the file is in the same directory.")
else:
    # --- 3. Sidebar Filters ---
    st.sidebar.header("🔍 Filter Preferences")

    # City Filter
    all_cities = sorted(df['city'].dropna().unique())
    selected_city = st.sidebar.selectbox("Choose a City", options=["All"] + all_cities)

    # Cuisine Filter
    all_cuisines = set()
    df['cuisine'].str.split(',').apply(lambda x: [all_cuisines.add(c.strip()) for c in x if isinstance(x, list)])
    sorted_cuisines = sorted(list(all_cuisines))
    selected_cuisine = st.sidebar.selectbox("Choose a Cuisine", options=["All"] + sorted_cuisines)

    # Price Filter (Strictly capped at 2000 as requested)
    max_price = st.sidebar.slider("Maximum Budget (₹)", min_value=0, max_value=2000, value=500, step=50)

    # Rating Filter
    min_rating = st.sidebar.slider("Minimum Rating", min_value=0.0, max_value=5.0, value=3.5, step=0.1)

    # --- 4. Recommendation Engine Logic ---
    filtered_df = df.copy()

    if selected_city != "All":
        filtered_df = filtered_df[filtered_df['city'] == selected_city]
    
    if selected_cuisine != "All":
        filtered_df = filtered_df[filtered_df['cuisine'].str.contains(selected_cuisine, case=False, na=False)]
        
    filtered_df = filtered_df[filtered_df['price'] <= max_price]
    filtered_df = filtered_df[filtered_df['rating_numeric'] >= min_rating]

    # Sort results by Rating (Best first) then Price (Cheaper first)
    recommendations = filtered_df.sort_values(by=['rating_numeric', 'price'], ascending=[False, True])

    # --- 5. Main Dashboard UI ---
    st.title("🍽️ Restaurant Recommendation Engine")
    st.markdown(f"Find the best dining spots in **{selected_city}** under **₹{max_price}**.")

    # Top Metrics
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Matches", len(recommendations))
    m2.metric("Avg Rating", f"{recommendations['rating_numeric'].mean():.1f} ⭐" if not recommendations.empty else "N/A")
    m3.metric("Market Avg Cost", f"₹{df['price'].mean():.0f}")
    m4.metric("Selection Avg Cost", f"₹{recommendations['price'].mean():.0f}" if not recommendations.empty else "N/A")

    st.divider()

    # Tabs for different views
    tab1, tab2, tab3 = st.tabs(["✨ Top Picks", "📋 Comparison Table", "📈 Market Analysis"])

    with tab1:
        if not recommendations.empty:
            # Highlight the #1 Recommendation
            top_pick = recommendations.iloc[0]
            st.subheader("Our Top Recommendation")
            with st.container(border=True):
                c1, c2 = st.columns([3, 1])
                with c1:
                    st.markdown(f"### {top_pick['name']}")
                    st.write(f"📍 **Address:** {top_pick.get('address', 'N/A')}")
                    st.write(f"🍴 **Cuisine:** {top_pick['cuisine']}")
                with c2:
                    st.metric("Rating", f"⭐ {top_pick['rating']}")
                    st.metric("Cost for Two", f"₹{top_pick['price']}")

            st.write("---")
            st.subheader("Other Great Options")
            # Show next top 5
            for i in range(1, min(6, len(recommendations))):
                row = recommendations.iloc[i]
                with st.expander(f"{row['name']} — ⭐ {row['rating']} — ₹{row['price']}"):
                    st.write(f"**Cuisine:** {row['cuisine']}")
                    st.write(f"**Location:** {row['city']}")
                    st.write(f"**Address:** {row.get('address', 'N/A')}")
        else:
            st.error("No restaurants found matching your criteria. Try reducing the rating or increasing the budget.")

    with tab2:
        st.subheader("Restaurant Comparison")
        if not recommendations.empty:
            display_df = recommendations[['name', 'city', 'rating', 'price', 'cuisine', 'address']].copy()
            display_df.columns = ['Name', 'City', 'Rating', 'Cost (₹)', 'Cuisine', 'Address']
            st.dataframe(display_df, use_container_width=True, hide_index=True)
        else:
            st.info("Filter the data to see the comparison table.")

    with tab3:
        if not recommendations.empty:
            col_v1, col_v2 = st.columns(2)
            with col_v1:
                st.write("**Price vs Rating (Selection in Red)**")
                fig1, ax1 = plt.subplots()
                sns.scatterplot(data=df, x='price', y='rating_numeric', color='lightgrey', alpha=0.3, label='Full Market', ax=ax1)
                sns.scatterplot(data=recommendations, x='price', y='rating_numeric', color='red', s=80, label='Selected', ax=ax1)
                ax1.set_xlabel("Cost (₹)")
                ax1.set_ylabel("Rating")
                st.pyplot(fig1)

            with col_v2:
                st.write("**Rating Density Distribution**")
                fig2, ax2 = plt.subplots()
                sns.kdeplot(df['rating_numeric'].dropna(), fill=True, label="Market", color="grey", ax=ax2)
                if len(recommendations) > 1:
                    sns.kdeplot(recommendations['rating_numeric'].dropna(), fill=True, label="Selected", color="red", ax=ax2)
                plt.legend()
                st.pyplot(fig2)
        else:
            st.write("Not enough data for visual analysis.")

    # Footer
    st.sidebar.divider()
    st.sidebar.caption(f"Search results: {len(recommendations)} / {len(df)}")

Overwriting app.py

In [ ]:
!streamlit run app.py

In [ ]:
import pickle
import pandas as pd

with open('encoder.pkl', 'rb') as file:
    loaded_mlb = pickle.load(file)

new_restaurant_cuisines = [
    ['Indian', 'Fast Food', 'Beverages'],
    ['Italian', 'Pizzas'],
    ['Desserts', 'Ice Cream'],
    ['Chinese', 'Asian']
]

print("Original new restaurant cuisines:")
for cuisine_list in new_restaurant_cuisines:
    print(cuisine_list)


projected_features = loaded_mlb.transform(new_restaurant_cuisines)

projected_df = pd.DataFrame(projected_features, columns=loaded_mlb.classes_)

print("\nProjected features for new restaurant cuisines (first 5 rows if more exist):")
print(projected_df.head())

print("\nThis `projected_df` can now be combined with other numerical features for prediction using a trained model.")